version: '3.8'
services:
  db:
    dns:
     - 8.8.8.8
     - 4.4.4.4
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=trivia
      - MYSQL_ROOT_PASSWORD=<root password>
      - MYSQL_USER=<user name>
      - MYSQL_PASSWORD=<user password>
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./mysql-files/trivia_schema_creation.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
